#!/usr/bin/env bash

# Update the system
sudo apt-get update
sudo apt-get upgrade -y

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

# Restart networking service to apply changes
sudo service networking restart

# Install Docker (assuming not already installed)
sudo apt-get install docker.io -y

# Run the checker on Docker
sudo docker run your-checker-image
